Workaround for MSVC Pybind11 Problem: Can't convert from python dict to json
pyuipc.init(config)
TypeError: init(): incompatible function arguments. The following argument types are supported:
    1. (arg0: json) -> None